#ifndef PLUGININTEFACE_GLOBAL_H
#define PLUGININTEFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGININTEFACE_LIBRARY)
#  define PLUGININTEFACE_EXPORT Q_DECL_EXPORT
#else
#  define PLUGININTEFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGININTEFACE_GLOBAL_H
