#ifndef CANINTERFACES_GLOBAL_H
#define CANINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CANINTERFACES_LIBRARY)
#  define CANINTERFACES_EXPORT Q_DECL_EXPORT
#else
#  define CANINTERFACES_EXPORT Q_DECL_IMPORT
#endif

#endif // CANINTERFACES_GLOBAL_H
