#ifndef CANSETTINGDIALOG_GLOBAL_H
#define CANSETTINGDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CANSETTINGDIALOG_LIBRARY)
#  define CANSETTINGDIALOG_EXPORT Q_DECL_EXPORT
#else
#  define CANSETTINGDIALOG_EXPORT Q_DECL_IMPORT
#endif

#endif
