#ifndef SERVERINTERFACE_GLOBAL_H
#define SERVERINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERINTERFACE_LIBRARY)
#  define SERVERINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define SERVERINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERINTERFACE_GLOBAL_H
